apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: w3h98wfl1-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/w3h98wfl1-java-quarkus-gitops